### ISSUE TITLE
Chatting after signing out and re-sign in 

### ISSUE THREAD

**Issue by dev-DTECH** [dev-DTECH/Network#2]
When you send a message after signing out and re-sign in the app will display a blank message after that message.

I have checked that the blank message is not sent in the server.

Please help.

**Comment by dev-abir** [comment]
I tried to run it locally. It's not asking me for signing up(rather a new bug?)

**Comment by dev-abir** [comment]
You may have configured something so that it only works in heroku. Not locally...

**Comment by dev-abir** [comment]
Okay... I have figured out the exact cause. The onSignIn(...) function adds an "onsubmit" event listener to the form. When the user logs out and again logs in, the "onsubmit" listener is added twice.
